#! /bin/sh

#Uncomment this line for auto en Virtual Machines
#xrandr --output Virtual-1 --auto

#change the Virtual-1 for diferent monitor running the command xrandr --listmonitors 
#this is a exemple
#     xrandr --listmonitors 
#     Monitors: 1
#     0: +*Virtual-1 1720/455x1402/371+0+0  Virtual-1



wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# RESOLUCION ARANDR


# WALLPAPER
feh --bg-fill ~/.config/Wallpaper/4rji.png

# POLYBAR
~/.config/polybar/launch.sh

# CUSTOM
bspc config focus_follows_pointer true

# PICOM
picom &
bspc config border_width 0

xsetroot -cursor_name left_ptr &
