#! /bin/sh


#para que funcione bien el monitor externo usbc samsung, ejecutar 1m, y luego 2m, y funciona 
alias 1m='xrandr -s 1920x1080'
alias 2m='xrandr --output eDP-1 --off --output DP-3 --primary --mode 1920x1080 --rate 60.00'

#barrier:
#alias barrer='flatpak run com.github.debauchee.barrier --config /home/nala/.config/barrier.conf & disown'

#para pantalla xps
#xrandr -s 1920x1200

#para pantalla externa unicamente y apagar interna
#xrandr --output eDP-1 --off --output DP-3 --primary --mode 2560x1440 --rate 60.00


wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# RESOLUCION ARANDR


# WALLPAPER
#feh --bg-fill ~/Wallpaper/Fondo.jpg
feh --bg-fill ~/.config/Wallpaper/Fondo.jpg


# POLYBAR
~/.config/polybar/launch.sh

# CUSTOM
bspc config focus_follows_pointer true

# PICOM
picom &
bspc config border_width 2

bspc config active_border_color '#a486dd'
bspc config normal_border_color '#fe8019'
bspc config focused_border_color '#a486dd'

xsetroot -cursor_name left_ptr &